openapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: >
        API de gestion d'une TODO List.
servers:
    -   url: http://localhost:8080
        description: Serveur local de développement

tags:
    -   name: tasks
        description: Opérations sur les tâches

paths:
    /tasks:
        get:
            tags: [ tasks ]
            summary: Récupérer toutes les tâches
            operationId: getTasks
            parameters:
                -   in: query
                    name: todo-only
                    required: false
                    description: Si true, retourne uniquement les tâches non complétées
                    schema:
                        type: boolean
            responses:
                '200':
                    description: Tâches trouvées avec succès
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Task'
                '204':
                    description: Aucune tâche trouvée
        post:
            tags: [ tasks ]
            summary: Créer une tâche
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskInput'
            responses:
                '201':
                    description: Tâche créée avec succès
                    headers:
                        Location:
                            description: URL de la ressource créée
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
        delete:
            tags: [ tasks ]
            summary: Supprimer toutes les tâches
            operationId: deleteAllTasks
            responses:
                '204':
                    description: Toutes les tâches supprimées
                '404':
                    description: Tâche non trouvée


    /tasks/count:
        get:
            tags: [ tasks ]
            summary: Récupérer le nombre de tâches
            operationId: countTasks
            responses:
                '200':
                    description: Nombre de tâches récupéré avec succès
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 3

    /tasks/{id}:
        parameters:
            -   in: path
                name: id
                required: true
                description: Identifiant numérique de la tâche
                schema:
                    type: integer
                    minimum: 1
        get:
            tags: [ tasks ]
            summary: Récupérer une tâche
            description: Récupérer une tâche par son identifiant
            operationId: getTaskById
            responses:
                '200':
                    description: Tâche trouvée avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: Tâche non trouvée
        put:
            tags: [ tasks ]
            summary: Modifier une tâche
            description: Modifier une tâche existante
            operationId: updateTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskInput'
            responses:
                '204':
                    description: Tâche modifiée avec succès
                '404':
                    description: Tâche non trouvée
        delete:
            tags: [ tasks ]
            summary: Supprimer une tâche
            description: Supprimer une tâche par son identifiant
            operationId: deleteTask
            responses:
                '204':
                    description: Tâche supprimée avec succès
                '404':
                    description: Tâche non trouvée

components:
    schemas:
        Task:
            type: object
            description: Représentation d'une tâche
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    nullable: true
                    example: Acheter du lait
                description:
                    type: string
                    nullable: true
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    nullable: true
                    example: false
            required:
                - id
                - title
        TaskInput:
            type: object
            description: Entrée pour créer ou modifier une tâche
            properties:
                title:
                    type: string
                    example: Acheter du lait
                description:
                    type: string
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    example: false
            required:
                - title
